[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[providers.docker]
  network = "traefik"
  exposedByDefault = false

[api]
  dashboard = false

[certificatesResolvers.letsencrypt.acme]
  email = "admin@thanayut.in.th"
  storage = "acme.json"
  [certificatesResolvers.letsencrypt.acme.tlsChallenge]